export const drinks =  [
      { id: "pepsi", name: "Pepsi", price: "2€", description: "Освежающий газированный напиток.", ingredients: ["Газированная вода", "Сахар", "Карамельный краситель", "Ортофосфорная кислота", "Кофеин"], imageKey: "pepsi" },
      { id: "pepsi_max", name: "Pepsi Max", price: "2€", description: "Газированный напиток без сахара с максимальным вкусом.", ingredients: ["Газированная вода", "Подсластители", "Карамельный краситель", "Ортофосфорная кислота", "Кофеин"], imageKey: "pepsi_max" },
      { id: "coca_cola", name: "Coca-Cola", price: "2€", description: "Классический газированный напиток.", ingredients: ["Газированная вода", "Сахар", "Карамельный краситель", "Ортофосфорная кислота", "Кофеин"], imageKey: "coca_cola" },
      { id: "brisa_laranja", name: "Brisa Лaranja", price: "2€", description: "Газированный напиток с апельсиновым вкусом.", ingredients: ["Газированная вода", "Сахар", "Концентрированный апельсиновый сок", "Лимонная кислота", "Натуральные ароматы"], imageKey: "brisa_laranja" },
      { id: "brisa_maracuja", name: "Brisa Маракуйя", price: "2€", description: "Газированный напиток с вкусом маракуйи.", ingredients: ["Газированная вода", "Сахар", "Концентрированный сок маракуйи", "Лимонная кислота", "Натуральные ароматы"], imageKey: "brisa_maracuja" },
      { id: "brisa_maca", name: "Brisa Яблоко", price: "2€", description: "Газированный напиток с яблочным вкусом.", ingredients: ["Газированная вода", "Сахар", "Концентрированный яблочный сок", "Лимонная кислота", "Натуральные ароматы"], imageKey: "brisa_maca" },
      { id: "laranjada", name: "Ларанжада", price: "2€", description: "Газированный напиток с апельсиновым вкусом.", ingredients: ["Газированная вода", "Сахар", "Концентрированный апельсиновый сок", "Лимонная кислота", "Натуральные ароматы"], imageKey: "laranjada" },
      { id: "compal_pessego", name: "Compal Персик", price: "2€", description: "Нектар из персика.", ingredients: ["Вода", "Пюре из персика", "Сахар", "Лимонная кислота", "Натуральные ароматы"], imageKey: "compal_pessego" },
      { id: "compal_maracuja", name: "Compal Маракуйя", price: "2€", description: "Нектар из маракуйи.", ingredients: ["Вода", "Пюре из маракуйи", "Сахар", "Лимонная кислота", "Натуральные ароматы"], imageKey: "compal_maracuja" },
      { id: "7up", name: "7UP", price: "2€", description: "Газированный напиток с вкусом лимона и лайма.", ingredients: ["Газированная вода", "Сахар", "Лимонная кислота", "Натуральные ароматы"], imageKey: "7up" },
      { id: "agua_033l", name: "Вода 0.33L", price: "2€", description: "Освежающая натуральная вода.", ingredients: ["Вода"], imageKey: "agua_033l" },
      { id: "agua_15l", name: "Вода 1.5L", price: "3€", description: "Освежающая натуральная вода.", ingredients: ["Вода"], imageKey: "agua_15l" },   
      { id: "coral_020", name: "Coral 0.20", price: "1.50€", description: "Лёгкое светлое пиво.", ingredients: ["Вода", "Ячменный солод", "Хмель", "Дрожжи"], imageKey: "coral_020" },
      { id: "coral_030", name: "Coral 0.30", price: "2€", description: "Освежающее светлое пиво.", ingredients: ["Вода", "Ячменный солод", "Хмель", "Дрожжи"], imageKey: "coral_030" },
      { id: "coral_050", name: "Coral 0.50", price: "3.5€", description: "Полное светлое пиво.", ingredients: ["Вода", "Ячменный солод", "Хмель", "Дрожжи"], imageKey: "coral_050" },
      { id: "heineken", name: "Heineken", price: "2.50€", description: "Международное светлое пиво.", ingredients: ["Вода", "Ячменный солод", "Хмель", "Дрожжи"], imageKey: "heineken" },
      { id: "corona", name: "Corona", price: "5€", description: "Светлое мексиканское пиво.", ingredients: ["Вода", "Ячменный солод", "Не солодовые зерна", "Хмель"], imageKey: "corona" },   
      { id: "mojito", name: "Мохито", price: "6€", description: "Освежающий кубинский коктейль с лаймом и мятой.", ingredients: ["Белый ром", "Сахар", "Сок лайма", "Газированная вода", "Мята"], imageKey: "mojito" },
      { id: "daikiri", name: "Дайкири", price: "6€", description: "Классический коктейль с ромом, лаймом и сахаром.", ingredients: ["Белый ром", "Сахар", "Сок лайма"], imageKey: "daikiri" },
      { id: "caipirinha", name: "Кайпиринья", price: "5€", description: "Бразильский коктейль с кашасой и лаймом.", ingredients: ["Кашаса", "Сахар", "Лайм"], imageKey: "caipirinha" },
      { id: "sangria_copo", name: "Сангрия в Стакане", price: "5.5€", description: "Традиционная сангрия.", ingredients: ["Красное вино", "Сахар", "Апельсиновый сок", "Газированная вода", "Нарезанные фрукты"], imageKey: "sangria_copo" },
      { id: "sangria_1l_2l", name: "Сангрия 1Л и 2Л", price: "16€ / 28€", description: "Кувшин традиционной сангрии.", ingredients: ["Красное вино", "Сахар", "Апельсиновый сок", "Газированная вода", "Нарезанные фрукты"], imageKey: "sangria_1l_2l" },
      { id: "aperol_spritz", name: "Апероль Шприц", price: "6€", description: "Итальянский коктейль с Апероль, Просекко и газированной водой.", ingredients: ["Апероль", "Просекко", "Газированная вода"], imageKey: "aperol_spritz" },
      { id: "mojito_maracuja", name: "Мохито Маракуйя", price: "6€", description: "Мохито с вкусом маракуйи.", ingredients: ["Белый ром", "Сахар", "Сок лайма", "Газированная вода", "Мята", "Маракуйя"], imageKey: "mojito_maracuja" },
      { id: "poncha_regional", name: "Региональная Понча", price: "3.50€", description: "Традиционный мадерийский коктейль с бренди.", ingredients: ["Бренди", "Мед", "Лимонный сок"], imageKey: "poncha_regional" },
      { id: "poncha_maracuja", name: "Понча Маракуйя", price: "3.50€", description: "Традиционный мадерийский коктейль с маракуйей.", ingredients: ["Бренди", "Мед", "Маракуйя"], imageKey: "poncha_maracuja" },
      { id: "carolans", name: "Кароланс", price: "4€", description: "Ирландский кремовый ликер.", ingredients: ["Ирландский виски", "Сливки", "Мед"], imageKey: "carolans" },
      { id: "pinha_colada", name: "Пина Колада", price: "5€", description: "Классический тропический коктейль с ромом и кокосовым молоком.", ingredients: ["Белый ром", "Кокосовое молоко", "Ананасовый сок"], imageKey: "pinha_colada" },
      { id: "cuba_libre", name: "Куба Либре (Ром)", price: "4€", description: "Классический коктейль с ромом и колой.", ingredients: ["Белый ром", "Кола", "Сок лайма"], imageKey: "cuba_livre_rum" },
      { id: "tequila_sunrise", name: "Текила Санрайз", price: "5€", description: "Яркий коктейль с текилой и гренадином.", ingredients: ["Текила", "Апельсиновый сок", "Гренадин"], imageKey: "tequila_sunrise" },
      { id: "irishcoffee", name: "Ирландский Кофе", price: "4.95€", description: "Кофейный коктейль с ирландским виски и сливками.", ingredients: ["Ирландский виски", "Кофе", "Сахар", "Сливки"], imageKey: "irishcoffee" },
      { id: "vodka", name: "Водка", price: "4€", description: "Классический дистиллят.", ingredients: ["Водка"], imageKey: "vodka" },
      { id: "jack_daniels", name: "Джек Дэниэлс", price: "4.5€", description: "Популярный теннессийский виски.", ingredients: ["Теннессийский виски"], imageKey: "jack_daniels" },
      { id: "black_level", name: "Блэк Левел", price: "5.5€", description: "Мягкий шотландский виски.", ingredients: ["Шотландский виски"], imageKey: "black_level" },
      { id: "red_level", name: "Ред Левел", price: "4.5€", description: "Смешанный шотландский виски.", ingredients: ["Шотландский виски"], imageKey: "red_level" },
      { id: "nikita", name: "Никита", price: "5€", description: "Освежающий коктейль с Мадейры с пивом и мороженым.", ingredients: ["Пиво", "Ванильное мороженое", "Ананас"], imageKey: "nikita" },
      { id: "baileyscoffee", name: "Кофе с Бэйлис", price: "5€", description: "Кремовый кофейный коктейль с Бэйлис.", ingredients: ["Ирландский крем Бэйлис", "Кофе"], imageKey: "baileyscoffee" }
    ];
  