export const drinks = [
   
      { id: "pepsi", name: "Pepsi", price: "2€", description: "Verfrissende cola drank.", ingredients: ["Koolzuurhoudend Water", "Suiker", "Karamelkleurstof", "Fosforzuur", "Cafeïne"], imageKey: "pepsi" },
      { id: "pepsi_max", name: "Pepsi Max", price: "2€", description: "Suikervrije cola drank met maximale smaak.", ingredients: ["Koolzuurhoudend Water", "Zoetstoffen", "Karamelkleurstof", "Fosforzuur", "Cafeïne"], imageKey: "pepsi_max" },
      { id: "coca_cola", name: "Coca-Cola", price: "2€", description: "Klassieke cola drank.", ingredients: ["Koolzuurhoudend Water", "Suiker", "Karamelkleurstof", "Fosforzuur", "Cafeïne"], imageKey: "coca_cola" },
      { id: "brisa_laranja", name: "Brisa Sinaasappel", price: "2€", description: "Verfrissende sinaasappelsoda.", ingredients: ["Koolzuurhoudend Water", "Suiker", "Sinaasappelsapconcentraat", "Citroenzuur", "Natuurlijke Aroma's"], imageKey: "brisa_laranja" },
      { id: "brisa_maracuja", name: "Brisa Passievrucht", price: "2€", description: "Soda met passievruchtsmaak.", ingredients: ["Koolzuurhoudend Water", "Suiker", "Passievruchtsapconcentraat", "Citroenzuur", "Natuurlijke Aroma's"], imageKey: "brisa_maracuja" },
      { id: "brisa_maca", name: "Brisa Appel", price: "2€", description: "Verfrissende appelsoda.", ingredients: ["Koolzuurhoudend Water", "Suiker", "Appelsapconcentraat", "Citroenzuur", "Natuurlijke Aroma's"], imageKey: "brisa_maca" },
      { id: "laranjada", name: "Sinaasappellimonade", price: "2€", description: "Soda met sinaasappelsmaak.", ingredients: ["Koolzuurhoudend Water", "Suiker", "Sinaasappelsapconcentraat", "Citroenzuur", "Natuurlijke Aroma's"], imageKey: "laranjada" },
      { id: "compal_pessego", name: "Compal Perzik", price: "2€", description: "Perziknectar drank.", ingredients: ["Water", "Perzikpulp", "Suiker", "Citroenzuur", "Natuurlijke Aroma's"], imageKey: "compal_pessego" },
      { id: "compal_maracuja", name: "Compal Passievrucht", price: "2€", description: "Passievruchtnectar drank.", ingredients: ["Water", "Passievruchtpulp", "Suiker", "Citroenzuur", "Natuurlijke Aroma's"], imageKey: "compal_maracuja" },
      { id: "7up", name: "7UP", price: "2€", description: "Citroen-limoensoda.", ingredients: ["Koolzuurhoudend Water", "Suiker", "Citroenzuur", "Natuurlijke Aroma's"], imageKey: "7up" },
      { id: "agua_033l", name: "Water 0.33L", price: "2€", description: "Verfrissend stil water.", ingredients: ["Water"], imageKey: "agua_033l" },
      { id: "agua_15l", name: "Water 1.5L", price: "3€", description: "Verfrissend stil water.", ingredients: ["Water"], imageKey: "agua_15l" },    
      { id: "coral_020", name: "Coral 0.20", price: "1.50€", description: "Lichte lagerbier.", ingredients: ["Water", "Gerstemout", "Hop", "Gist"], imageKey: "coral_020" },
      { id: "coral_030", name: "Coral 0.30", price: "2€", description: "Verfrissende lagerbier.", ingredients: ["Water", "Gerstemout", "Hop", "Gist"], imageKey: "coral_030" },
      { id: "coral_050", name: "Coral 0.50", price: "3.5€", description: "Volledig lagerbier.", ingredients: ["Water", "Gerstemout", "Hop", "Gist"], imageKey: "coral_050" },
      { id: "heineken", name: "Heineken", price: "2.50€", description: "Internationaal bekend lagerbier.", ingredients: ["Water", "Gerstemout", "Hop", "Gist"], imageKey: "heineken" },
      { id: "corona", name: "Corona", price: "5€", description: "Mexicaanse pale lagerbier.", ingredients: ["Water", "Gerstemout", "Niet-geëeste Granen", "Hop"], imageKey: "corona" },
      { id: "mojito", name: "Mojito", price: "6€", description: "Verfrissende Cubaanse cocktail met limoen en munt.", ingredients: ["Witte Rum", "Suiker", "Limoensap", "Sodawater", "Munt"], imageKey: "mojito" },
      { id: "daikiri", name: "Daikiri", price: "6€", description: "Klassieke cocktail met rum, limoen en suiker.", ingredients: ["Witte Rum", "Suiker", "Limoensap"], imageKey: "daikiri" },
      { id: "caipirinha", name: "Caipirinha", price: "5€", description: "Braziliaanse cocktail met cachaça en limoen.", ingredients: ["Cachaça", "Suiker", "Limoen"], imageKey: "caipirinha" },
      { id: "sangria_copo", name: "Sangria Glas", price: "5.5€", description: "Glas traditionele sangria.", ingredients: ["Rode Wijn", "Suiker", "Sinaasappelsap", "Sodawater", "Fruitsnippers"], imageKey: "sangria_copo" },
      { id: "sangria_1l_2l", name: "Sangria 1L & 2L", price: "16€ / 28€", description: "Karaf traditionele sangria.", ingredients: ["Rode Wijn", "Suiker", "Sinaasappelsap", "Sodawater", "Fruitsnippers"], imageKey: "sangria_1l_2l" },
      { id: "aperol_spritz", name: "Aperol Spritz", price: "6€", description: "Italiaanse cocktail met Aperol, prosecco en soda.", ingredients: ["Aperol", "Prosecco", "Sodawater"], imageKey: "aperol_spritz" },
      { id: "mojito_maracuja", name: "Passievrucht Mojito", price: "6€", description: "Mojito met passievruchtsmaak.", ingredients: ["Witte Rum", "Suiker", "Limoensap", "Sodawater", "Munt", "Passievrucht"], imageKey: "mojito_maracuja" },
      { id: "poncha_regional", name: "Regionale Poncha", price: "3.50€", description: "Traditionele Madeirense cocktail met aguardente.", ingredients: ["Aguardente", "Honing", "Citroensap"], imageKey: "poncha_regional" },
      { id: "poncha_maracuja", name: "Passievrucht Poncha", price: "3.50€", description: "Poncha met passievruchtsmaak.", ingredients: ["Aguardente", "Honing", "Passievruchtsap"], imageKey: "poncha_maracuja" },
      { id: "poncha_pescador", name: "Vissers Poncha", price: "3.50€", description: "Poncha van vissers met citroen en honing.", ingredients: ["Aguardente", "Honing", "Citroensap"], imageKey: "poncha_pescador" },
      { id: "carolans", name: "Carolans", price: "5€", description: "Zachte Ierse roomlikeur.", ingredients: ["Ierse Whisky", "Room", "Honing"], imageKey: "carolans" },
      { id: "pinha_colada", name: "Piña Colada", price: "5€", description: "Klassieke tropische cocktail met rum en kokosmelk.", ingredients: ["Witte Rum", "Kokosmelk", "Ananassap"], imageKey: "pinha_colada" },
      { id: "cuba_libre", name: "Cuba Libre (Rum)", price: "4€", description: "Klassieke cocktail met rum en cola.", ingredients: ["Witte Rum", "Cola", "Limoensap"], imageKey: "cuba_livre_rum" },
      { id: "tequila_sunrise", name: "Tequila Sunrise", price: "5€", description: "Levendige cocktail met tequila en grenadine.", ingredients: ["Tequila", "Sinaasappelsap", "Grenadine"], imageKey: "tequila_sunrise" },
      { id: "irishcoffee", name: "Irish Coffee", price: "4.95€", description: "Koffie cocktail met Ierse whisky en room.", ingredients: ["Ierse Whisky", "Koffie", "Suiker", "Room"], imageKey: "irishcoffee" },
      { id: "vodka", name: "Vodka", price: "4€", description: "Klassieke gedistilleerde drank.", ingredients: ["Vodka"], imageKey: "vodka" },
      { id: "jack_daniels", name: "Jack Daniels", price: "4.5€", description: "Populaire Tennessee whisky.", ingredients: ["Tennessee Whisky"], imageKey: "jack_daniels" },
      { id: "black_level", name: "Black Level", price: "5.5€", description: "Zachte gemengde Scotch whisky.", ingredients: ["Scotch Whisky"], imageKey: "black_level" },
      { id: "red_level", name: "Red Level", price: "4.5€", description: "Gemengde Scotch whisky.", ingredients: ["Scotch Whisky"], imageKey: "red_level" },
      { id: "nikita", name: "Nikita", price: "5€", description: "Verfrissende Madeirense cocktail met bier en ijs.", ingredients: ["Bier", "Vanille-ijs", "Ananas"], imageKey: "nikita" },
      { id: "baileyscoffee", name: "Baileys Coffee", price: "5€", description: "Romige koffiecocktail met Baileys.", ingredients: ["Baileys Irish Cream", "Koffie"], imageKey: "baileyscoffee" }
    ];
  