export const drinks = [
      { id: "pepsi", name: "Pepsi", price: "2€", description: "Освіжаючий газований напій.", ingredients: ["Газована вода", "Цукор", "Карамельний колір", "Ортофосфорна кислота", "Кофеїн"], imageKey: "pepsi" },
      { id: "pepsi_max", name: "Pepsi Max", price: "2€", description: "Газований напій без цукру з максимальним смаком.", ingredients: ["Газована вода", "Подсластители", "Карамельний колір", "Ортофосфорна кислота", "Кофеїн"], imageKey: "pepsi_max" },
      { id: "coca_cola", name: "Coca-Cola", price: "2€", description: "Класичний газований напій.", ingredients: ["Газована вода", "Цукор", "Карамельний колір", "Ортофосфорна кислота", "Кофеїн"], imageKey: "coca_cola" },
      { id: "brisa_laranja", name: "Brisa Апельсин", price: "2€", description: "Газований напій з апельсиновим смаком.", ingredients: ["Газована вода", "Цукор", "Концентрований апельсиновий сік", "Лимонна кислота", "Натуральні аромати"], imageKey: "brisa_laranja" },
      { id: "brisa_maracuja", name: "Brisa Маракуйя", price: "2€", description: "Газований напій зі смаком маракуї.", ingredients: ["Газована вода", "Цукор", "Концентрований сік маракуї", "Лимонна кислота", "Натуральні аромати"], imageKey: "brisa_maracuja" },
      { id: "brisa_maca", name: "Brisa Яблуко", price: "2€", description: "Газований напій з яблучним смаком.", ingredients: ["Газована вода", "Цукор", "Концентрований яблучний сік", "Лимонна кислота", "Натуральні аромати"], imageKey: "brisa_maca" },
      { id: "laranjada", name: "Laranjada", price: "2€", description: "Газований напій з апельсиновим смаком.", ingredients: ["Газована вода", "Цукор", "Концентрований апельсиновий сік", "Лимонна кислота", "Натуральні аромати"], imageKey: "laranjada" },
      { id: "compal_pessego", name: "Compal Персик", price: "2€", description: "Нектар з персика.", ingredients: ["Вода", "Пюре персика", "Цукор", "Лимонна кислота", "Натуральні аромати"], imageKey: "compal_pessego" },
      { id: "compal_maracuja", name: "Compal Маракуйя", price: "2€", description: "Нектар з маракуї.", ingredients: ["Вода", "Пюре маракуї", "Цукор", "Лимонна кислота", "Натуральні аромати"], imageKey: "compal_maracuja" },
      { id: "7up", name: "7UP", price: "2€", description: "Газований напій зі смаком лимону і лайму.", ingredients: ["Газована вода", "Цукор", "Лимонна кислота", "Натуральні аромати"], imageKey: "7up" },
      { id: "agua_033l", name: "Вода 0.33L", price: "2€", description: "Освіжаюча природна вода.", ingredients: ["Вода"], imageKey: "agua_033l" },
      { id: "agua_15l", name: "Вода 1.5L", price: "3€", description: "Освіжаюча природна вода.", ingredients: ["Вода"], imageKey: "agua_15l" },   
      { id: "coral_020", name: "Coral 0.20", price: "1.50€", description: "Легке світле пиво.", ingredients: ["Вода", "Ячмінний солод", "Хміль", "Дріжджі"], imageKey: "coral_020" },
      { id: "coral_030", name: "Coral 0.30", price: "2€", description: "Освіжаюче світле пиво.", ingredients: ["Вода", "Ячмінний солод", "Хміль", "Дріжджі"], imageKey: "coral_030" },
      { id: "coral_050", name: "Coral 0.50", price: "3.5€", description: "Повноцінне світле пиво.", ingredients: ["Вода", "Ячмінний солод", "Хміль", "Дріжджі"], imageKey: "coral_050" },
      { id: "heineken", name: "Heineken", price: "2.50€", description: "Міжнародне світле пиво.", ingredients: ["Вода", "Ячмінний солод", "Хміль", "Дріжджі"], imageKey: "heineken" },
      { id: "corona", name: "Corona", price: "5€", description: "Мексиканське світле пиво.", ingredients: ["Вода", "Ячмінний солод", "Немалтовані зерна", "Хміль"], imageKey: "corona" },   
      { id: "mojito", name: "Мохіто", price: "6€", description: "Освіжаючий кубинський коктейль з лаймом і м'ятою.", ingredients: ["Білий ром", "Цукор", "Сік лайма", "Газована вода", "М'ята"], imageKey: "mojito" },
      { id: "daikiri", name: "Дайкірі", price: "6€", description: "Класичний коктейль з ромом, лаймом і цукром.", ingredients: ["Білий ром", "Цукор", "Сік лайма"], imageKey: "daikiri" },
      { id: "caipirinha", name: "Кайпірінья", price: "5€", description: "Бразильський коктейль з кашасою і лаймом.", ingredients: ["Кашаса", "Цукор", "Лайм"], imageKey: "caipirinha" },
      { id: "sangria_copo", name: "Сангрія в Склянці", price: "5.5€", description: "Традиційна сангрія.", ingredients: ["Червоне вино", "Цукор", "Апельсиновий сік", "Газована вода", "Порізані фрукти"], imageKey: "sangria_copo" },
      { id: "sangria_1l_2l", name: "Сангрія 1L і 2L", price: "16€ / 28€", description: "Глечик традиційної сангрії.", ingredients: ["Червоне вино", "Цукор", "Апельсиновий сік", "Газована вода", "Порізані фрукти"], imageKey: "sangria_1l_2l" },
      { id: "aperol_spritz", name: "Апероль Шпріц", price: "6€", description: "Італійський коктейль з Аперолем, Просекко і газованою водою.", ingredients: ["Апероль", "Просекко", "Газована вода"], imageKey: "aperol_spritz" },
      { id: "mojito_maracuja", name: "Мохіто з Маракуйєю", price: "6€", description: "Мохіто зі смаком маракуї.", ingredients: ["Білий ром", "Цукор", "Сік лайма", "Газована вода", "М'ята", "Маракуйя"], imageKey: "mojito_maracuja" },
      { id: "poncha_regional", name: "Регіональна Понча", price: "3.50€", description: "Традиційний коктейль Мадейри з бренді.", ingredients: ["Бренді", "Мед", "Лимонний сік"], imageKey: "poncha_regional" },
      { id: "caipirinha_maracuja", name: "Кайпірінья з Маракуйєю", price: "5€", description: "Бразильський коктейль з кашасою і маракуйєю.", ingredients: ["Кашаса", "Цукор", "Лайм", "Маракуйя"], imageKey: "caipirinha_maracuja" },
      { id: "carolans", name: "Carolans", price: "4€", description: "Ірландський кремовий лікер.", ingredients: ["Ірландський віскі", "Крем", "Мед"], imageKey: "carolans" },
      { id: "pinha_colada", name: "Піна Колада", price: "5€", description: "Класичний тропічний коктейль з ромом і кокосовим молоком.", ingredients: ["Білий ром", "Кокосове молоко", "Ананасовий сік"], imageKey: "pinha_colada" },
      { id: "cuba_libre", name: "Куба Лібре (Ром)", price: "4€", description: "Класичний коктейль з ромом і колою.", ingredients: ["Білий ром", "Кола", "Сік лайма"], imageKey: "cuba_livre_rum" },
      { id: "tequila_sunrise", name: "Текіла Санрайз", price: "5€", description: "Яскравий коктейль з текілою і гренадином.", ingredients: ["Текіла", "Апельсиновий сік", "Гренадин"], imageKey: "tequila_sunrise" },
      { id: "irishcoffee", name: "Ірландська кава", price: "4.95€", description: "Кавовий коктейль з ірландським віскі і вершками.", ingredients: ["Ірландський віскі", "Кава", "Цукор", "Вершки"], imageKey: "irishcoffee" },
      { id: "vodka", name: "Водка", price: "4€", description: "Класичний дистилят.", ingredients: ["Водка"], imageKey: "vodka" },
      { id: "jack_daniels", name: "Jack Daniel's", price: "4.5€", description: "Популярний віскі з Теннессі.", ingredients: ["Віскі з Теннессі"], imageKey: "jack_daniels" },
      { id: "black_level", name: "Black Level", price: "5.5€", description: "М'який шотландський віскі.", ingredients: ["Шотландський віскі"], imageKey: "black_level" },
      { id: "red_level", name: "Red Level", price: "4.5€", description: "Змішаний шотландський віскі.", ingredients: ["Шотландський віскі"], imageKey: "red_level" },
      { id: "nikita", name: "Нікіта", price: "5€", description: "Освіжаючий коктейль з Мадейри з пивом і морозивом.", ingredients: ["Пиво", "Ванільне морозиво", "Ананас"], imageKey: "nikita" },
      { id: "baileyscoffee", name: "Кава з Baileys", price: "5€", description: "Кремовий кавовий коктейль з Baileys.", ingredients: ["Ірландський крем Baileys", "Кава"], imageKey: "baileyscoffee" }
    ];
  