export const drinks = [
   
      { id: "pepsi", name: "Pepsi", price: "2€", description: "Refreshing cola beverage.", ingredients: ["Carbonated Water", "Sugar", "Caramel Color", "Phosphoric Acid", "Caffeine"], imageKey: "pepsi" },
      { id: "pepsi_max", name: "Pepsi Max", price: "2€", description: "Sugar-free cola beverage with maximum taste.", ingredients: ["Carbonated Water", "Sweeteners", "Caramel Color", "Phosphoric Acid", "Caffeine"], imageKey: "pepsi_max" },
      { id: "coca_cola", name: "Coca-Cola", price: "2€", description: "Classic cola beverage.", ingredients: ["Carbonated Water", "Sugar", "Caramel Color", "Phosphoric Acid", "Caffeine"], imageKey: "coca_cola" },
      { id: "brisa_laranja", name: "Brisa Orange", price: "2€", description: "Refreshing orange soda.", ingredients: ["Carbonated Water", "Sugar", "Orange Juice Concentrate", "Citric Acid", "Natural Flavors"], imageKey: "brisa_laranja" },
      { id: "brisa_maracuja", name: "Brisa Passion Fruit", price: "2€", description: "Passion fruit flavored soda.", ingredients: ["Carbonated Water", "Sugar", "Passion Fruit Juice Concentrate", "Citric Acid", "Natural Flavors"], imageKey: "brisa_maracuja" },
      { id: "brisa_maca", name: "Brisa Apple", price: "2€", description: "Refreshing apple soda.", ingredients: ["Carbonated Water", "Sugar", "Apple Juice Concentrate", "Citric Acid", "Natural Flavors"], imageKey: "brisa_maca" },
      { id: "laranjada", name: "Orangeade", price: "2€", description: "Orange flavored soda.", ingredients: ["Carbonated Water", "Sugar", "Orange Juice Concentrate", "Citric Acid", "Natural Flavors"], imageKey: "laranjada" },
      { id: "compal_pessego", name: "Compal Peach", price: "2€", description: "Peach nectar beverage.", ingredients: ["Water", "Peach Pulp", "Sugar", "Citric Acid", "Natural Flavors"], imageKey: "compal_pessego" },
      { id: "compal_maracuja", name: "Compal Passion Fruit", price: "2€", description: "Passion fruit nectar beverage.", ingredients: ["Water", "Passion Fruit Pulp", "Sugar", "Citric Acid", "Natural Flavors"], imageKey: "compal_maracuja" },
      { id: "7up", name: "7UP", price: "2€", description: "Lemon-lime soda.", ingredients: ["Carbonated Water", "Sugar", "Citric Acid", "Natural Flavors"], imageKey: "7up" },
      { id: "agua_033l", name: "Water 0.33L", price: "2€", description: "Refreshing still water.", ingredients: ["Water"], imageKey: "agua_033l" },
      { id: "agua_15l", name: "Water 1.5L", price: "3€", description: "Refreshing still water.", ingredients: ["Water"], imageKey: "agua_15l" },
      { id: "coral_020", name: "Coral 0.20", price: "1.50€", description: "Light lager beer.", ingredients: ["Water", "Barley Malt", "Hops", "Yeast"], imageKey: "coral_020" },
      { id: "coral_030", name: "Coral 0.30", price: "2€", description: "Refreshing lager beer.", ingredients: ["Water", "Barley Malt", "Hops", "Yeast"], imageKey: "coral_030" },
      { id: "coral_050", name: "Coral 0.50", price: "3.5€", description: "Full-bodied lager beer.", ingredients: ["Water", "Barley Malt", "Hops", "Yeast"], imageKey: "coral_050" },
      { id: "heineken", name: "Heineken", price: "2.50€", description: "Internationally renowned lager beer.", ingredients: ["Water", "Barley Malt", "Hops", "Yeast"], imageKey: "heineken" },
      { id: "corona", name: "Corona", price: "5€", description: "Mexican pale lager beer.", ingredients: ["Water", "Barley Malt", "Non-malted Cereals", "Hops"], imageKey: "corona" },
      { id: "mojito", name: "Mojito", price: "6€", description: "Refreshing Cuban cocktail with lime and mint.", ingredients: ["White Rum", "Sugar", "Lime Juice", "Soda Water", "Mint"], imageKey: "mojito" },
      { id: "daikiri", name: "Daikiri", price: "6€", description: "Classic cocktail with rum, lime, and sugar.", ingredients: ["White Rum", "Sugar", "Lime Juice"], imageKey: "daikiri" },
      { id: "caipirinha", name: "Caipirinha", price: "5€", description: "Brazilian cocktail with cachaça and lime.", ingredients: ["Cachaça", "Sugar", "Lime"], imageKey: "caipirinha" },
      { id: "sangria_copo", name: "Sangria Glass", price: "5.5€", description: "Glass of traditional sangria.", ingredients: ["Red Wine", "Sugar", "Orange Juice", "Soda Water", "Fruit Slices"], imageKey: "sangria_copo" },
      { id: "sangria_1l_2l", name: "Sangria 1L & 2L", price: "16€ / 28€", description: "Pitcher of traditional sangria.", ingredients: ["Red Wine", "Sugar", "Orange Juice", "Soda Water", "Fruit Slices"], imageKey: "sangria_1l_2l" },
      { id: "aperol_spritz", name: "Aperol Spritz", price: "6€", description: "Italian cocktail with Aperol, prosecco, and soda.", ingredients: ["Aperol", "Prosecco", "Soda Water"], imageKey: "aperol_spritz" },
      { id: "mojito_maracuja", name: "Passion Fruit Mojito", price: "6€", description: "Passion fruit flavored mojito.", ingredients: ["White Rum", "Sugar", "Lime Juice", "Soda Water", "Mint", "Passion Fruit"], imageKey: "mojito_maracuja" },
      { id: "poncha_regional", name: "Regional Poncha", price: "3.50€", description: "Traditional Madeiran cocktail with aguardente.", ingredients: ["Aguardente", "Honey", "Lemon Juice"], imageKey: "poncha_regional" },
      { id: "poncha_maracuja", name: "Passion Fruit Poncha", price: "3.50€", description: "Passion fruit flavored poncha.", ingredients: ["Aguardente", "Honey", "Passion Fruit Juice"], imageKey: "poncha_maracuja" },
      { id: "poncha_pescador", name: "Fisherman's Poncha", price: "3.50€", description: "Fisherman's poncha with lemon and honey.", ingredients: ["Aguardente", "Honey", "Lemon Juice"], imageKey: "poncha_pescador" },
      { id: "carolans", name: "Carolans", price: "5€", description: "Smooth Irish cream liqueur.", ingredients: ["Irish Whiskey", "Cream", "Honey"], imageKey: "carolans" },
      { id: "pinha_colada", name: "Piña Colada", price: "6€", description: "Tropical cocktail with rum, coconut, and pineapple.", ingredients: ["White Rum", "Coconut Cream", "Pineapple Juice"], imageKey: "pinha_colada" },
      { id: "cuba_livre_rum", name: "Cuba Libre (Rum)", price: "4€", description: "Classic cocktail with rum and cola.", ingredients: ["White Rum", "Cola", "Lime"], imageKey: "cuba_livre_rum" },
      { id: "tequila_sunrise", name: "Tequila Sunrise", price: "5€", description: "Vibrant cocktail with tequila and orange juice.", ingredients: ["Tequila", "Orange Juice", "Grenadine"], imageKey: "tequila_sunrise" },
      { id: "irishcoffee", name: "Irish Coffee", price: "4.95€", description: "Hot coffee cocktail with Irish whiskey and cream.", ingredients: ["Irish Whiskey", "Coffee", "Sugar", "Cream"], imageKey: "irishcoffee" },
      { id: "vodka", name: "Vodka", price: "4€", description: "Classic distilled spirit.", ingredients: ["Vodka"], imageKey: "vodka" },
      { id: "jack_daniels", name: "Jack Daniels", price: "4.5€", description: "Popular Tennessee whiskey.", ingredients: ["Tennessee Whiskey"], imageKey: "jack_daniels" },
      { id: "black_level", name: "Black Level", price: "5.5€", description: "Smooth blended Scotch whisky.", ingredients: ["Scotch Whisky"], imageKey: "black_level" },
      { id: "red_level", name: "Red Level", price: "4.5€", description: "Blended Scotch whisky.", ingredients: ["Scotch Whisky"], imageKey: "red_level" },
      { id: "nikita", name: "Nikita", price: "5€", description: "Refreshing Madeiran cocktail with beer and ice cream.", ingredients: ["Beer", "Vanilla Ice Cream", "Pineapple"], imageKey: "nikita" },
      { id: "baileyscoffee", name: "Baileys Coffee", price: "5€", description: "Creamy coffee cocktail with Baileys.", ingredients: ["Baileys Irish Cream", "Coffee"], imageKey: "baileyscoffee" }
    ];
  