export const drinks =  [
      { id: "pepsi", name: "Pepsi", price: "2€", description: "Erfrischendes kohlensäurehaltiges Getränk.", ingredients: ["Kohlensäurehaltiges Wasser", "Zucker", "Karamellfarbstoff", "Phosphorsäure", "Koffein"], imageKey: "pepsi" },
      { id: "pepsi_max", name: "Pepsi Max", price: "2€", description: "Zuckerfreies kohlensäurehaltiges Getränk mit maximalem Geschmack.", ingredients: ["Kohlensäurehaltiges Wasser", "Süßstoffe", "Karamellfarbstoff", "Phosphorsäure", "Koffein"], imageKey: "pepsi_max" },
      { id: "coca_cola", name: "Coca-Cola", price: "2€", description: "Klassisches kohlensäurehaltiges Getränk.", ingredients: ["Kohlensäurehaltiges Wasser", "Zucker", "Karamellfarbstoff", "Phosphorsäure", "Koffein"], imageKey: "coca_cola" },
      { id: "brisa_laranja", name: "Brisa Orange", price: "2€", description: "Erfrischendes Orangen-Limonaden-Getränk.", ingredients: ["Kohlensäurehaltiges Wasser", "Zucker", "Orangensaftkonzentrat", "Zitronensäure", "Natürliche Aromen"], imageKey: "brisa_laranja" },
      { id: "brisa_maracuja", name: "Brisa Passion", price: "2€", description: "Limonade mit Passionsfruchtgeschmack.", ingredients: ["Kohlensäurehaltiges Wasser", "Zucker", "Passionsfruchtkonzentrat", "Zitronensäure", "Natürliche Aromen"], imageKey: "brisa_maracuja" },
      { id: "brisa_maca", name: "Brisa Apfel", price: "2€", description: "Erfrischende Apfel-Limonade.", ingredients: ["Kohlensäurehaltiges Wasser", "Zucker", "Apfelsaftkonzentrat", "Zitronensäure", "Natürliche Aromen"], imageKey: "brisa_maca" },
      { id: "laranjada", name: "Orangenlimonade", price: "2€", description: "Limonade mit Orangengeschmack.", ingredients: ["Kohlensäurehaltiges Wasser", "Zucker", "Orangensaftkonzentrat", "Zitronensäure", "Natürliche Aromen"], imageKey: "laranjada" },
      { id: "compal_pessego", name: "Compal Pfirsich", price: "2€", description: "Pfirsich-Nektar.", ingredients: ["Wasser", "Pfirsichpulpe", "Zucker", "Zitronensäure", "Natürliche Aromen"], imageKey: "compal_pessego" },
      { id: "compal_maracuja", name: "Compal Passion", price: "2€", description: "Passionsfrucht-Nektar.", ingredients: ["Wasser", "Passionsfruchtpulpe", "Zucker", "Zitronensäure", "Natürliche Aromen"], imageKey: "compal_maracuja" },
      { id: "7up", name: "7UP", price: "2€", description: "Zitronen-Limetten-Limonade.", ingredients: ["Kohlensäurehaltiges Wasser", "Zucker", "Zitronensäure", "Natürliche Aromen"], imageKey: "7up" },
      { id: "agua_033l", name: "Wasser 0.33L", price: "2€", description: "Erfrischendes stilles Wasser.", ingredients: ["Wasser"], imageKey: "agua_033l" },
      { id: "agua_15l", name: "Wasser 1.5L", price: "3€", description: "Erfrischendes stilles Wasser.", ingredients: ["Wasser"], imageKey: "agua_15l" },    
      { id: "coral_020", name: "Coral 0.20", price: "1.50€", description: "Leichtes Lagerbier.", ingredients: ["Wasser", "Gerstenmalz", "Hopfen", "Hefe"], imageKey: "coral_020" },
      { id: "coral_030", name: "Coral 0.30", price: "2€", description: "Erfrischendes Lagerbier.", ingredients: ["Wasser", "Gerstenmalz", "Hopfen", "Hefe"], imageKey: "coral_030" },
      { id: "coral_050", name: "Coral 0.50", price: "3.5€", description: "Vollmundiges Lagerbier.", ingredients: ["Wasser", "Gerstenmalz", "Hopfen", "Hefe"], imageKey: "coral_050" },
      { id: "heineken", name: "Heineken", price: "2.50€", description: "Internationales Lagerbier.", ingredients: ["Wasser", "Gerstenmalz", "Hopfen", "Hefe"], imageKey: "heineken" },
      { id: "corona", name: "Corona", price: "5€", description: "Mexikanisches helles Lagerbier.", ingredients: ["Wasser", "Gerstenmalz", "Nicht gemälzte Getreide", "Hopfen"], imageKey: "corona" },   
      { id: "mojito", name: "Mojito", price: "6€", description: "Erfrischender kubanischer Cocktail mit Limette und Minze.", ingredients: ["Weißer Rum", "Zucker", "Limettensaft", "Sodawasser", "Minze"], imageKey: "mojito" },
      { id: "daikiri", name: "Daiquiri", price: "6€", description: "Klassischer Cocktail mit Rum, Limette und Zucker.", ingredients: ["Weißer Rum", "Zucker", "Limettensaft"], imageKey: "daikiri" },
      { id: "caipirinha", name: "Caipirinha", price: "5€", description: "Brasilianischer Cocktail mit Cachaça und Limette.", ingredients: ["Cachaça", "Zucker", "Limette"], imageKey: "caipirinha" },
      { id: "sangria_copo", name: "Sangria Glas", price: "5.5€", description: "Glas traditioneller Sangria.", ingredients: ["Rotwein", "Zucker", "Orangensaft", "Sodawasser", "Obststücke"], imageKey: "sangria_copo" },
      { id: "sangria_1l_2l", name: "Sangria 1L & 2L", price: "16€ / 28€", description: "Krug traditioneller Sangria.", ingredients: ["Rotwein", "Zucker", "Orangensaft", "Sodawasser", "Obststücke"], imageKey: "sangria_1l_2l" },
      { id: "aperol_spritz", name: "Aperol Spritz", price: "6€", description: "Italienischer Cocktail mit Aperol, Prosecco und Sodawasser.", ingredients: ["Aperol", "Prosecco", "Sodawasser"], imageKey: "aperol_spritz" },
      { id: "mojito_maracuja", name: "Mojito Passion", price: "6€", description: "Mojito mit Passionsfruchtgeschmack.", ingredients: ["Weißer Rum", "Zucker", "Limettensaft", "Sodawasser", "Minze", "Passionsfrucht"], imageKey: "mojito_maracuja" },
      { id: "poncha_regional", name: "Poncha Regional", price: "3.50€", description: "Traditioneller Madeira-Cocktail mit Aguardente.", ingredients: ["Aguardente", "Honig", "Zitronensaft"], imageKey: "poncha_regional" },
      { id: "poncha_maracuja", name: "Poncha Passion", price: "3.50€", description: "Poncha mit Passionsfruchtgeschmack.", ingredients: ["Aguardente", "Honig", "Passionsfruchtsaft"], imageKey: "poncha_maracuja" },
      { id: "poncha_pescador", name: "Poncha Fischer", price: "3.50€", description: "Poncha der Fischer mit Zitrone und Honig.", ingredients: ["Aguardente", "Honig", "Zitronensaft"], imageKey: "poncha_pescador" },
      { id: "carolans", name: "Carolans", price: "5€", description: "Irischer Sahnelikör.", ingredients: ["Irischer Whiskey", "Sahne", "Honig"], imageKey: "carolans" },
      { id: "pinha_colada", name: "Pina Colada", price: "5€", description: "Klassischer tropischer Cocktail mit Rum und Kokosnussmilch.", ingredients: ["Weißer Rum", "Kokosnussmilch", "Ananassaft"], imageKey: "pinha_colada" },
      { id: "cuba_libre", name: "Cuba Libre (Rum)", price: "4€", description: "Klassischer Cocktail mit Rum und Cola.", ingredients: ["Weißer Rum", "Cola", "Limettensaft"], imageKey: "cuba_livre_rum" },
      { id: "tequila_sunrise", name: "Tequila Sunrise", price: "5€", description: "Lebhafter Cocktail mit Tequila und Grenadine.", ingredients: ["Tequila", "Orangensaft", "Grenadine"], imageKey: "tequila_sunrise" },
      { id: "irishcoffee", name: "Irish Coffee", price: "4.95€", description: "Kaffee-Cocktail mit irischem Whiskey und Sahne.", ingredients: ["Irischer Whiskey", "Kaffee", "Zucker", "Sahne"], imageKey: "irishcoffee" },
      { id: "vodka", name: "Wodka", price: "4€", description: "Klassisches destilliertes Getränk.", ingredients: ["Wodka"], imageKey: "vodka" },
      { id: "jack_daniels", name: "Jack Daniels", price: "4.5€", description: "Beliebter Tennessee Whiskey.", ingredients: ["Tennessee Whiskey"], imageKey: "jack_daniels" },
      { id: "black_level", name: "Black Level", price: "5.5€", description: "Weicher und gemischter schottischer Whisky.", ingredients: ["Schottischer Whisky"], imageKey: "black_level" },
      { id: "red_level", name: "Red Level", price: "4.5€", description: "Gemischter schottischer Whisky.", ingredients: ["Schottischer Whisky"], imageKey: "red_level" },
      { id: "nikita", name: "Nikita", price: "5€", description: "Erfrischender Madeira-Cocktail mit Bier und Eis.", ingredients: ["Bier", "Vanilleeis", "Ananas"], imageKey: "nikita" },
      { id: "baileyscoffee", name: "Baileys Kaffee", price: "5€", description: "Cremiger Kaffee-Cocktail mit Baileys.", ingredients: ["Baileys Irish Cream", "Kaffee"], imageKey: "baileyscoffee" }
    ];
  